services:
  backend-db:
    image: postgres:16
    container_name: backend-db
    restart: always
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  api-db:
    image: postgres:16
    container_name: api-db
    restart: always
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: apiuser
      POSTGRES_PASSWORD: apipass
    ports:
      - "5434:5432"
    volumes:
      - api-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

volumes:
  backend-db-data:
  api-db-data:

networks:
  backend-network:
    driver: bridge